--3
INSERT INTO Proveedores (codigpro, cifpro, nombrpro, direcpro, cpostpro,
localpro, telefpro, faxpro, procepro) VALUES ('P005', 'A12345678', 'Gomez Sanz,
Antonio', 'Mayor,18', '26070', 'Logroño', '(34) 942 202 022', '(34) 941 123 123', 'UE');

--4
UPDATE PROVEEDORES SET EMAILPRO = 'mailto:gil@cancan.es' WHERE NOMBRPRO = 'Gil Perez, Jon';

--5
DELETE FROM PROVEEDORES WHERE LOCALPRO = 'Logroño';

--6
SELECT * FROM ARTICULOS;

--7
SELECT NOMBRPRO, TELEFPRO FROM PROVEEDORES;

--8
SELECT *
FROM ARTICULOS A
WHERE A.PREUNART > 180 AND A.STOCKART <= 100;

--9
SELECT *
FROM ARTICULOS A
WHERE A.PREUNART BETWEEN 180 AND 300;

--10
SELECT *
FROM PROVEEDORES P
WHERE LOCALPRO IN ('Pamplona', 'Donosti', 'Barcelona');

--11
SELECT CODIGPRO, NOMBRPRO, DIRECPRO, CPOSTPRO, LOCALPRO
FROM PROVEEDORES
WHERE NOMBRPRO BETWEEN 'A' AND 'H';

--12
SELECT CODIGPRO, NOMBRPRO, DIRECPRO, CPOSTPRO, LOCALPRO, TELEFPRO
FROM PROVEEDORES
WHERE EMAILPRO IS NULL;

--13
SELECT UNIQUE P.CODIGPRO, P.NOMBRPRO, P.DIRECPRO, P.LOCALPRO
FROM PROVEEDORES P
INNER JOIN PEDIDOS PE ON (P.CODIGPRO = PE.CODIGPRO)
WHERE PE.FECHAPED BETWEEN '20/1/2022' AND '15/9/2022';

--14
SELECT A.CODIGART, A.DESCRART
FROM ARTICULOS A 
INNER JOIN LINEAS L ON (L.CODIGART = A.CODIGART)
INNER JOIN PEDIDOS P ON (L.NUMPED = P.NUMPED)
WHERE FECHAPED BETWEEN '15/5/2022' AND '30/5/2022';

--15                                                 --ESPECIAL
SELECT P.NUMPED, L1.NUMLIN, A.CODIGART
FROM LINEAS L1, LINEAS L2, PEDIDOS P, ARTICULOS A
WHERE L1.NUMPED = L2.NUMPED
AND L1.CODIGART = A.CODIGART
AND L1.NUMPED = P.NUMPED
AND L1.CODIGART = L2.CODIGART
AND L1.NUMLIN <> L2.NUMLIN;

--16
SELECT CASE
    WHEN A.PREUNART > 200 THEN A.PREUNART
    ELSE 10
END AS mi_precio
FROM ARTICULOS A;

--17
SELECT P.CODIGPRO, P.NOMBRPRO
FROM PROVEEDORES P
INNER JOIN PEDIDOS PE ON (PE.CODIGPRO = P.CODIGPRO)
WHERE P.LOCALPRO = 'Donosti'
AND PE.FECHAPED BETWEEN '24/09/2022' AND '21/11/2022';

--18
SELECT COUNT(A.CODIGART) CANTIDAD, MAX(A.PREUNART) MAX,  MIN(A.PREUNART) MIN, AVG(A.PREUNART) PRECIO, SUM(A.STOCKART * A.PREUNART) VALORACION
FROM ARTICULOS A;

--19
SELECT PE.NUMPED, PE.FECHAPED, EXTRACT(DAY FROM PE.FECHAPED) DIA_MES, EXTRACT(MONTH FROM PE.FECHAPED) MES, EXTRACT(YEAR FROM PE.FECHAPED) AÑO, TO_CHAR(PE.FECHAPED, 'DAY') DIA_SEM
FROM PEDIDOS PE;

--20
SELECT P.NUMPED, SUM(L.PREUNLIN * L.UNILIN * (1-L.DESCULIN/100)) IMPORTE
FROM PEDIDOS P
INNER JOIN LINEAS L ON (L.NUMPED = P.NUMPED)
GROUP BY P.NUMPED;

--21
SELECT P.NUMPED, SUM(L.PREUNLIN * L.UNILIN * (1-L.DESCULIN/100)) IMPORTE
FROM PEDIDOS P
INNER JOIN LINEAS L ON (L.NUMPED = P.NUMPED)
GROUP BY P.NUMPED
HAVING COUNT(*) > 1;

--22
SELECT A.DESCRART, L.NUMPED, SUM(L.UNILIN)
FROM PEDIDOS P
INNER JOIN LINEAS L ON (L.NUMPED = P.NUMPED)
INNER JOIN ARTICULOS A ON (L.CODIGART = A.CODIGART)
GROUP BY L.NUMPED, A.DESCRART
ORDER BY A.DESCRART ASC;

--23
CREATE TABLE T1 AS SELECT P.NUMPED, SUM(L.PREUNLIN * L.UNILIN * (1-L.DESCULIN/100)) IMPORTE
FROM PEDIDOS P
INNER JOIN LINEAS L ON (L.NUMPED = P.NUMPED)
GROUP BY P.NUMPED
HAVING COUNT(*) > 1;

SELECT *
FROM T1;

//DROP TABLE T1;

--24
UPDATE ARTICULOS SET PREUNART =
(CASE 
    WHEN PREUNART < 200 THEN PREUNART*1.07
    ELSE PREUNART * 1.05
END);

SELECT CODIGART,DESCRART,PREUNART
FROM ARTICULOS;

--25
DELETE FROM PROVEEDORES WHERE PROCEPRO != 'UE';

--26
CREATE TABLE FABRICA(
    CODIGO NUMBER,
    NOMBRE CHAR (25) UNIQUE,
    CONSTRAINT PK_CODIGO PRIMARY KEY (CODIGO)
);
CREATE TABLE FABRICAR(
    CODIGOFABRICA NUMBER,
    CODIGART CHAR (6 BYTE),
    CONSTRAINT PK_CODFABRICA PRIMARY KEY (CODIGOFABRICA,CODIGART),
    CONSTRAINT CODIGOFABRICA_FK FOREIGN KEY (CODIGOFABRICA) REFERENCES  FABRICA (CODIGO),
    CONSTRAINT CODIGART_FK FOREIGN KEY (CODIGART) REFERENCES ARTICULOS (CODIGART)
);
CREATE TABLE PLANTA(
    NOMBRE CHAR (25 BYTE),
    POBLACION CHAR (25 BYTE),
    CLASIFICACION,
    SUPERFICIE NUMBER (2),
    CERCANIA CHAR (2),
    COSTE NUMBER,
    CONSTRAINT CERCANIACK 
    
    



