-- 8
INSERT INTO EQUIPO (CODEQU, NOMEQUIPO) VALUES (CODEQU_SEQ.NEXTVAL, 'SIN EQUIPO');

CREATE SEQUENCE codequ_seq START WITH 23;

CREATE OR REPLACE TRIGGER BAJA_EQUIPO
BEFORE DELETE ON EQUIPO
FOR EACH ROW
BEGIN
    UPDATE CICLISTA SET CODEQU = 221
    WHERE CODEQU = :OLD.CODEQU;
END;
/

DELETE FROM EQUIPO WHERE NOMEQUIPO = 'Amore Vita';

ALTER TABLE CICLISTA DROP CONSTRAINT FK_CICL_EQUIPO;
ALTER TABLE CICLISTA ADD CONSTRAINT FK_CICL_EQUIPO FOREIGN KEY (CODEQU) REFERENCES EQUIPO(CODEQU);

DELETE FROM EQUIPO WHERE NOMEQUIPO = 'ONCE';

SELECT * FROM ESTADISTICAS;

-- 9
CREATE OR REPLACE TRIGGER BORRA_ACTUALIZA_EQUIPO
AFTER DELETE OR UPDATE OF CODEQU ON EQUIPO
FOR EACH ROW
BEGIN
    IF :OLD.NOMEQUIPO = 'SIN EQUIPO' THEN 
        raise_application_error(-20002, 'EL EQUIPO '|| :OLD.NOMEQUIPO ||' NO SE PUEDE BORRAR NI CAMBIAR SU CODIGO');
    END IF;
END;
/

DELETE FROM EQUIPO WHERE NOMEQUIPO = 'SIN EQUIPO';

-- 10
CREATE OR REPLACE TRIGGER ALTA_EQUIPO
AFTER INSERT ON EQUIPO
FOR EACH ROW
BEGIN
    UPDATE CICLISTA SET CODEQU = :NEW.CODEQU
    WHERE CODEQU = 221;
END;
/

INSERT INTO EQUIPO (CODEQU, NOMEQUIPO, DIRECTOR) VALUES (CODEQU_SEQ.NEXTVAL, 'Liberty Seguros', 'Manuel Saiz');

SELECT * FROM CICLISTA WHERE CODEQU = 43;


-- 11

DELETE FROM EQUIPO WHERE NOMEQUIPO = 'Banesto';

INSERT INTO EQUIPO (CODEQU, NOMEQUIPO, DIRECTOR) VALUES (CODEQU_SEQ.NEXTVAL, 'Movistar Team', 'Miguel Echevarria');

SELECT * FROM CICLISTA WHERE CODEQU = 49;












