//1

SELECT  AVG (SUM (L.CANT*L.PRECIO)) "MEDIA_FACTURA"
FROM LINEAS_FAC L
JOIN FACTURAS F ON (L.CODFAC = F.CODFAC)
GROUP BY F.CODFAC;

SELECT AVG (SUMA_FACTURA) AS MEDIA_FACTURA
FROM (SELECT SUM (L.CANT*L.PRECIO) AS SUMA_FACTURA
FROM LINEAS_FAC L
JOIN FACTURAS F ON (L.CODFAC = F.CODFAC)
GROUP BY F.CODFAC);


//2

SELECT MAX(COUNT(*)) "MAXIMO"
FROM CLIENTES C
JOIN PUEBLOS P ON (P.CODPUE = C.CODPUE)
GROUP BY P.CODPUE;

SELECT MAX (NUM_CLIENTES) "MAXIMO"
FROM (SELECT COUNT (*) AS NUM_CLIENTES
FROM PUEBLOS P 
JOIN CLIENTES C ON (P.CODPUE = C.CODPUE)
GROUP BY P.CODPUE);

//3

SELECT MAX (COUNT(*)) "Nº facturas"
FROM CLIENTES C
JOIN FACTURAS F ON (C.CODCLI = F.CODCLI)
GROUP BY C.CODCLI;

SELECT MAX (NUM_FACTURAS) "Nº facturas"
FROM (SELECT COUNT (*) AS NUM_FACTURAS
FROM CLIENTES C
JOIN FACTURAS F ON (C.CODCLI = F.CODCLI)
GROUP BY C.CODCLI);

//4

SELECT V.NOMBRE, A.DESCRIP, L.PRECIO
FROM VENDEDORES V
JOIN LINEAS_FAC L ON (V.CODVEN = L.CODVEN)
JOIN ARTICULOS A ON (L.CODART = A.CODART)
WHERE L.PRECIO = (SELECT MIN (PRECIO) FROM LINEAS_FAC);

//5

SELECT COUNT(CLIENTES_SIN) "Clientes no iva 16"
FROM (SELECT DISTINCT (F.CODCLI) CLIENTES_SIN
FROM FACTURAS F
MINUS
SELECT F.CODCLI
FROM FACTURAS F
WHERE F.IVA = 16);

SELECT COUNT (DISTINCT(C.CODCLI)) AS Clientes_no_iva_16
FROM CLIENTES C
JOIN FACTURAS F ON (C.CODCLI = F.CODCLI)
WHERE C.CODCLI NOT IN (
    SELECT F.CODCLI 
    FROM FACTURAS F	
    WHERE F.IVA = 16);

//6

SELECT L.CODFAC
FROM LINEAS_FAC L
WHERE L.PRECIO = (SELECT MAX (L.PRECIO)
FROM LINEAS_FAC L);

//7

SELECT COUNT(NO_COMPRADOS)
FROM (SELECT A.CODART AS NO_COMPRADOS
    FROM ARTICULOS A
    MINUS
    SELECT L.CODART
    FROM LINEAS_FAC L);
    
//8

SELECT C.NOMBRE
FROM CLIENTES C
WHERE C.CODCLI NOT IN (SELECT F.CODCLI
FROM FACTURAS F)
ORDER BY C.NOMBRE ASC;

//9

SELECT COUNT (NO_CLIENTES)
FROM (SELECT P.CODPUE AS NO_CLIENTES
    FROM PUEBLOS P
    MINUS
    SELECT C.CODPUE
    FROM CLIENTES C);

//10

SELECT COUNT(CLI_SOLO_16) "CLIENTE_SOLO_16"
FROM (SELECT DISTINCT F.CODCLI AS CLI_SOLO_16
      FROM FACTURAS F
      WHERE F.IVA = 16
      MINUS
      SELECT F.CODCLI
      FROM FACTURAS F
      WHERE F.IVA != 16 OR F.IVA IS NULL);
      
//11

SELECT DISTINCT A1.DESCRIP, COUNT(DISTINCT(A1.CODART)) AS REPETICIONES
FROM ARTICULOS A1, ARTICULOS A2
WHERE A1.DESCRIP = A2.DESCRIP AND A1.CODART != A2.CODART
GROUP BY A1.DESCRIP;

CREATE TABLE DUPLICADOS AS SELECT DISTINCT A1.CODART, A1.DESCRIP, A1.PRECIO
FROM ARTICULOS A1, ARTICULOS A2
WHERE A1.DESCRIP = A2.DESCRIP AND A1.CODART != A2.CODART;

//DROP TABLE DUPLICADOS CASCADE CONSTRAINT;
//SELECT * FROM DUPLICADOS;

//12

DELETE FROM DUPLICADOS WHERE CODART IN (SELECT D1.CODART
FROM DUPLICADOS D1
WHERE D1.PRECIO <= ALL (SELECT D2.PRECIO 
                        FROM DUPLICADOS D2
                        WHERE D1.DESCRIP = D2.DESCRIP AND D1.CODART != D2.CODART));

CREO QUE EL D1.CODART != D2.CODART SE PODRIA QUITAR
                        
//13    

INSERT INTO DUPLICADOS(
SELECT DISTINCT A1.CODART, A1.DESCRIP, A1.PRECIO
FROM ARTICULOS A1, ARTICULOS A2
WHERE A1.DESCRIP = A2.DESCRIP AND A1.CODART != A2.CODART
MINUS
SELECT *
FROM DUPLICADOS);

//14

SELECT DISTINCT A.CODART, A.DESCRIP, A.STOCK
FROM ARTICULOS A, LINEAS_FAC L
WHERE A.CODART = L.CODART AND A.STOCK > ALL (SELECT(L.CANT)
                    FROM LINEAS_FAC L
                    WHERE A.CODART = L.CODART);

//Relacionas con lineas_fac para que así no se metan articulos no vendidos en lineas de las facturas

//15

ALTER TABLE facturas ADD total number(8,2);

UPDATE FACTURAS F SET TOTAL = (SELECT SUM(L.PRECIO*L.CANT)
                            FROM LINEAS_FAC L
                            WHERE F.CODFAC = L.CODFAC
                            GROUP BY L.CODFAC);
                            
//SELECT * FROM FACTURAS;

UPDATE FACTURAS F SET TOTAL = (SELECT SUM(L.PRECIO*L.CANT*(1-F.DTO)
                            FROM LINEAS_FAC L
                            WHERE F.CODFAC = L.CODFAC AND F.IVA IS NOT NULL AND F.DTO IS NOT 				NULL
                            GROUP BY L.CODFAC);
METER IVA DELANTE DEL SUM
CAMBIAR COMPROBACION IS NULL CON NVL

//16

//21

SELECT EXTRACT (MONTH FROM FECHA) "MES", COUNT(CODFAC) "FACTURAS"
FROM FACTURAS
WHERE CODCLI IN (SELECT DISTINCT CODCLI
                    FROM FACTURAS
                    WHERE FECHA <= '31/12/2022' AND FECHA >= '01/01/2022'
                    HAVING COUNT(DISTINCT(CODFAC)) > 1 
                    GROUP BY CODCLI)
AND FECHA BETWEEN '01/01/2022' AND '31/12/2022'
GROUP BY EXTRACT(MONTH FROM FECHA)
ORDER BY EXTRACT(MONTH FROM FECHA) ASC;

//22

SELECT EXTRACT (MONTH FROM FECHA) "MES", CODCLI ,COUNT(CODFAC) "FACTURAS"
FROM FACTURAS
WHERE CODCLI IN (SELECT DISTINCT CODCLI
                    FROM FACTURAS
                    WHERE FECHA <= '31/12/2022' AND FECHA >= '01/01/2022'
                    HAVING COUNT(DISTINCT(CODFAC)) > 1 
                    GROUP BY CODCLI)
AND FECHA BETWEEN '01/01/2022' AND '31/12/2022'
GROUP BY EXTRACT(MONTH FROM FECHA), CODCLI
ORDER BY EXTRACT(MONTH FROM FECHA) ASC, CODCLI ASC;

//23

SELECT COUNT(CODART) "ARTÍCULOS"
FROM (
        SELECT A.CODART
        FROM ARTICULOS A
        WHERE A.STOCK > 5 AND A.PRECIO > 3
        MINUS
        SELECT A.CODART
        FROM FACTURAS F
        LEFT JOIN LINEAS_FAC L ON (F.CODFAC = L.CODFAC)
        LEFT JOIN ARTICULOS A ON (L.CODART = A.CODART)
        AND F.FECHA >= '01/09/2021' AND F.FECHA <= '31/12/2021');

//24

SELECT C.*
FROM FACTURAS F
JOIN CLIENTES C ON (F.CODCLI = C.CODCLI)
MINUS
SELECT C.*
FROM FACTURAS F
JOIN CLIENTES C ON (F.CODCLI = C.CODCLI)
WHERE EXTRACT (MONTH FROM FECHA) BETWEEN 4 AND 12;

//25
SELECT P.NOMBRE, COUNT (DISTINCT C.CODCLI)
FROM PROVINCIAS P
LEFT JOIN PUEBLOS PU USING (CODPRO) 
LEFT JOIN CLIENTES C ON (C.CODPUE = PU.CODPUE AND C.CODCLI IN (
                                                    SELECT CODCLI
                                                    FROM FACTURAS
                                                    WHERE FECHA BETWEEN '1/1/2022' AND '31/12/2022'
                                                    MINUS
                                                    SELECT CODCLI
                                                    FROM FACTURAS
                                                    WHERE FECHA BETWEEN '1/1/2022' AND '31/12/2022' AND (IVA IS NULL OR IVA = 0)))
GROUP BY P.NOMBRE
ORDER BY P.NOMBRE;

SELECT P.NOMBRE, COUNT (DISTINCT C.CODCLI)
FROM PROVINCIAS P
LEFT JOIN PUEBLOS PU USING (CODPRO) 
LEFT JOIN CLIENTES C ON (C.CODPUE = PU.CODPUE)
WHERE C.CODCLI IN (
                    SELECT CODCLI
                    FROM FACTURAS
                    WHERE FECHA BETWEEN '1/1/2022' AND '31/12/2022'
                    MINUS
                    SELECT CODCLI
                    FROM FACTURAS
                    WHERE FECHA BETWEEN '1/1/2022' AND '31/12/2022' AND (IVA IS NULL OR IVA = 0))
GROUP BY P.NOMBRE
ORDER BY P.NOMBRE;

