# Generated by Django 5.1.2 on 2024-10-25 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizForgeExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=50)),
                ('score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='QuizForgeExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=30)),
                ('start_date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('questions', models.ManyToManyField(to='exams.quizforgeexamquestion')),
            ],
        ),
        migrations.CreateModel(
            name='QuizForgeExamQuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_option', models.CharField(max_length=30)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.quizforgeexamquestion')),
            ],
        ),
        migrations.AddField(
            model_name='quizforgeexamquestion',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.quizforgeexamquestionchoice'),
        ),
    ]
