# Generated by Django 5.1.2 on 2024-10-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizforgeexam',
            options={'permissions': [('create_exam', 'Can create exam'), ('assign_exam', 'Can assign exam to students')]},
        ),
        migrations.AlterModelOptions(
            name='quizforgeexamquestion',
            options={'permissions': [('create_question', 'Can create question')]},
        ),
    ]
