# Generated by Django 5.1.2 on 2024-10-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_quizforgeexam_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizforgeexam',
            options={'permissions': [('create_exam', 'Can create exam'), ('assign_exam', 'Can assign exam to students'), ('view_exam', 'Can view exam')]},
        ),
    ]
