# Generated by Django 4.2.7 on 2024-10-26 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_quizforgeuser_delete_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exams", "0003_alter_quizforgeexam_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quizforgeexam",
            options={"permissions": [("assign_exam", "Assign exam to student")]},
        ),
        migrations.AlterModelOptions(
            name="quizforgeexamquestion",
            options={},
        ),
        migrations.RenameField(
            model_name="quizforgeexam",
            old_name="duration",
            new_name="duration_minutes",
        ),
        migrations.RemoveField(
            model_name="quizforgeexamquestion",
            name="solution",
        ),
        migrations.AddField(
            model_name="quizforgeexam",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="quizforgeexam",
            name="exam_name",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="quizforgeexamquestion",
            name="statement",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="quizforgeexamquestionchoice",
            name="answer_option",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="quizforgeexamquestionchoice",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choices",
                to="exams.quizforgeexamquestion",
            ),
        ),
    ]
