# Generated by Django 4.2.7 on 2024-10-27 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0004_alter_quizforgeexam_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizforgeexam',
            name='assigned_students',
            field=models.ManyToManyField(related_name='assigned_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
