# Generated by Django 4.2.7 on 2024-10-28 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_quizforgeexamquestionanswersubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizforgeexamquestionanswersubmission',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='exams.quizforgeexamquestionchoice'),
        ),
    ]
