# Generated by Django 5.1.2 on 2024-11-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_quizforgeexamquestionanswersubmission_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizforgeexamquestion',
            name='is_multiple_choice',
            field=models.BooleanField(default=False),
        ),
    ]
