# .gitlab-ci.yml

image: node:16

stages:
  - deploy

deploy_to_heroku:
  stage: deploy
  tags:
    - deploy
  script:
    # Install Heroku CLI
    - curl https://cli-assets.heroku.com/install.sh | sh
    # Log into Heroku using the API key
    - echo "$HEROKU_API_KEY" | heroku auth:token
    # Push code to Heroku's Git
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/gpi1.git
    - git push heroku devel:main
  only:
    - main
    - devel
