// 19

SELECT D.CURSO "CURSO",MAX (A.ALUMNOS) "MAYOR_NUM_ALUMNOS",MIN(A.ALUMNOS) "MENOR_NUM_ALUMNOS",AVG(A.ALUMNOS) "MEDIA_NUM_ALUMNOS"
FROM DOCENCIA D, ASIGNATURAS A
WHERE A.SIGLAS = D.SIGLAS
GROUP BY D.CURSO;

//20

SELECT L.NOMBRE "NOMBRE",L.EDIFICIO "EDIFICIO", MAX(D.CURSO) "CURSO_MAS_ALTO"
FROM LOCALES L, DOCENCIA D
WHERE L.CODIGO = D.LOCAL
GROUP BY L.NOMBRE, L.EDIFICIO
ORDER BY L.NOMBRE;

//21

SELECT A.NOMBRE "NOMBRE", D.DIA "DIA", COUNT (DISTINCT P.CODIGO) "PROFESORES_NO_TIEMPO_COMPLETO"
FROM ASIGNATURAS A, DOCENCIA D, PROFESORES P
WHERE A.SIGLAS = D.SIGLAS AND D.PROFESOR = P.CODIGO AND P.DEDICACION != 'TC' 
GROUP BY A.NOMBRE, D.DIA
HAVING COUNT (DISTINCT P.CODIGO) > 1;

//22

SELECT A.CURSO "CURSO",(A.NOMBRE || '('|| A.SIGLAS|| ')') AS ASIGNATURA , A.GRUPOS_TEORIA "TOTAL_GRUPOS_TEORIA", A.GRUPOS_PRACTICA "TOTAL_GRUPOS_PRACTICA"
FROM ASIGNATURAS A
WHERE A.CREDITOS > 9 AND A.GRUPOS_TEORIA > 0 AND A.GRUPOS_PRACTICA > 0
ORDER BY A.CURSO, A.NOMBRE;

//23

SELECT (A.NOMBRE || '('|| A.SIGLAS|| ')') AS ASIGNATURA , A.ALUMNOS /COUNT (*)"ALUMNOS_POR_CLASE"
FROM ASIGNATURAS A,DOCENCIA D
WHERE A.SIGLAS=D.SIGLAS
GROUP BY A.NOMBRE, A.SIGLAS,A.ALUMNOS
ORDER BY "ALUMNOS_POR_CLASE" DESC;

//24

SELECT G.NOMBRE AS GRUPO, COUNT (DISTINCT D.PROFESOR) "DISTINTOS_PROFESORES"
FROM DOCENCIA D, GRUPOS G
WHERE D.CURSO=G.CURSO AND D.CLASE=G.CLASE AND D.GRUPO=G.CODIGO
GROUP BY G.NOMBRE;

//25

SELECT G.NOMBRE "GRUPO"
FROM GRUPOS G, DOCENCIA D
WHERE D.CURSO=G.CURSO AND D.CLASE=G.CLASE AND D.GRUPO=G.CODIGO
HAVING COUNT(DISTINCT D.PROFESOR) = 1
GROUP BY G.NOMBRE;

//26

SELECT (P.APELLIDO1 || P.APELLIDO2 || ','|| P.NOMBRE_PILA ) AS NOMBRE_Y_APELLIDOS, COUNT (DISTINCT A.NOMBRE) "CUENTA_ASIGNATURAS" --se podria hacer con d.siglas y asi no añades asignaturas
FROM PROFESORES P, ASIGNATURAS A, DOCENCIA D
WHERE P.CODIGO = D.PROFESOR AND D.SIGLAS = A.SIGLAS
GROUP BY P.APELLIDO1, P.APELLIDO2, P.NOMBRE_PILA;
// HAVING COUNT(DISTINCT D.PROFESOR) = 1  //se podria suprimir al hacerlo ya en el group by


//27

SELECT (P.APELLIDO1 || ' ' || P.APELLIDO2 || ', '|| P.NOMBRE_PILA ) "NOMBRE_Y_APELLIDOS"
FROM PROFESORES P, DOCENCIA D
WHERE P.CODIGO = D.PROFESOR
GROUP BY P.APELLIDO1, P.APELLIDO2, P.NOMBRE_PILA
HAVING COUNT(DISTINCT D.SIGLAS) > 1
ORDER BY "NOMBRE_Y_APELLIDOS";

//28





