//1
SELECT D.CODIGO || ' ' || D.NOMBRE "COD NOMBRE", A.CODIGO || ' ' || A.NOMBRE "COD NOMBRE" FROM DEPARTAMENTOS D, AREAS A WHERE A.DEPARTAMENTO = D.CODIGO ORDER BY D.CODIGO, A.CODIGO;

//2
SELECT D.* FROM DOCENCIA D, LOCALES L WHERE D.LOCAL = L.CODIGO AND L.CAPACIDAD > 100 AND D.CURSO = 1;


//3
SELECT DISTINCT P.CODIGO , P.APELLIDO1 || ' ' || P.APELLIDO2 || ' ' || P.NOMBRE_PILA "NOMBREYAPELLIDOS"
FROM DOCENCIA D, PROFESORES P,ASIGNATURAS A
WHERE P.CODIGO=D.PROFESOR AND D.SIGLAS= A.SIGLAS AND A.NOMBRE ='Bases de Datos';

// 4
SELECT G.*,D.*
FROM GRUPOS G, DOCENCIA D
WHERE G.CLASE=D.CLASE AND G.CURSO=D.CURSO AND G.CODIGO=D.GRUPO AND G.CLASE=D.CLASE  AND D.SIGLAS = 'BDa';

//5
SELECT DISTINCT P.CODIGO,P.NOMBRE_PILA,A.NOMBRE,A.ALUMNOS
FROM PROFESORES P,ASIGNATURAS A,DOCENCIA D
WHERE P.CODIGO = D.PROFESOR AND D.SIGLAS = A.SIGLAS ORDER BY A.ALUMNOS DESC,P.CODIGO ASC; // ASC,DESC

//6
SELECT DISTINCT (DD.NOMBRE || ' (' || DD.CODIGO || ')' ) AS NombreyDepartamnto ,G.NOMBRE
FROM DEPARTAMENTOS DD, GRUPOS G, AREAS A, PROFESORES P, DOCENCIA D
WHERE DD.CODIGO = A.DEPARTAMENTO AND A.CODIGO = P.AREA AND P.CODIGO = D.PROFESOR AND D.CURSO=G.CURSO AND D.CLASE=G.CLASE AND D.GRUPO=G.CODIGO;
//7
SELECT DISTINCT A.SIGLAS,A.NOMBRE,D.DIA,D.HORA,L.CODIGO,L.NOMBRE
FROM ASIGNATURAS A, DOCENCIA D, LOCALES L
WHERE A.SIGLAS=D.SIGLAS AND D.LOCAL=L.CODIGO AND (A.ANUALIDAD IS NULL OR A.SIGLAS='BDa' OR A.SIGLAS='ACo' OR A.SIGLAS='DES' OR A.SIGLAS='Eco' OR A.SIGLAS = 'Fis-G')
ORDER BY A.SIGLAS ASC,D.HORA DESC;
//8
SELECT DISTINCT A.NOMBRE,G.NOMBRE, (A.ALUMNOS/A.GRUPOS_PRACTICA) AS ALUMNOSxGRUPO
FROM ASIGNATURAS A, DOCENCIA D, GRUPOS G
WHERE A.SIGLAS = D.SIGLAS AND D.CURSO = G.CURSO AND D.CLASE = G.CLASE AND D.GRUPO = G.CODIGO
AND D.CLASE = 'P' AND (D.HORA < 11.3 OR D.HORA > 19.3) 
ORDER BY ALUMNOSxGRUPO DESC,A.NOMBRE ASC, G.NOMBRE ASC;
