//1 Y 2

DESC DEPHOSPITAL;
DESC EMPLEADO;
DESC HOSPITAL;
DESC INGRESOS;
DESC PACIENTE;
DESC TRABAJA;

--2: visualizar tablas:
SELECT * FROM DEPHOSPITAL;
SELECT * FROM  EMPLEADO;
SELECT * FROM  HOSPITAL;
SELECT * FROM  INGRESOS;
SELECT * FROM  PACIENTE;
SELECT * FROM  TRABAJA;

-- 'donde trabajan los empleados': PODRIA HABER EMPLEADOS QUE NO TENGAN NINGUN REGISTRO EN LA TABLA TRABAJA (EMPELADOS INACTIVOS)
-- 'donde trabajan los empleados' = CRUZAR EMPLEADO Y TRABAJA, PARA COGER SOLO LOS EMPLEADOS QUE TRABAJAN EN ALGUN HOSPITAL.
SELECT *
     FROM empleado e, trabaja t
     WHERE e.dni=t.dni;

-- 'empleados que hayan atendido los ingresos': PODRIA HABER EMPLEADOS QUE NO HAYAN ATENDIDO NINGUN INGRESO (NO TENGA ESE EMPLEADO NINGUN REGISTRO EN LA TABLA INGRESOS)
-- 'empleados que hayan atendido los ingresos' =  CRUZAR EMPLEADO Y INGRESOS, PARA COGER SOLO LOS EMPLEADOS QUE HAN ATENDIDO ALGUN INGRESO
SELECT *
     FROM empleado e, ingresos i
     WHERE e.dni=i.dni;

//3
 
SELECT CODHOSP, NOMHOSP, NUMEMP
FROM HOSPITAL
WHERE HOSPITAL.CIUDAD = 'Pamplona';

//4

SELECT COUNT(*)"TOTAL"
FROM HOSPITAL;

//5

SELECT COUNT(*)"TOTAL"
FROM HOSPITAL
WHERE HOSPITAL.NUMEMP >4;

//6

SELECT E.*
FROM EMPLEADO E
ORDER BY E.CUALIFICACION;

//7

SELECT COUNT(*) "TOT_AUXILIARES"
FROM EMPLEADO E
WHERE E.CUALIFICACION = 'AUXILIAR';

//8

SELECT COUNT(*) "TOT_AUX_DEPD3"
FROM EMPLEADO E
WHERE E.CUALIFICACION = 'AUXILIAR' AND E.DEPAR = 'D3';

//9

SELECT H.NOMHOSP, COUNT(*) "TOT_AUX_DEPD3"
FROM EMPLEADO E, HOSPITAL H, TRABAJA T
WHERE E.CUALIFICACION = 'AUXILIAR' AND E.DEPAR = 'D3' AND E.DNI = T.DNI AND T.CODHOSP = H.CODHOSP
GROUP BY H.NOMHOSP;

//10

SELECT E.DNI, E.NOMBRE, E.DEPAR
FROM EMPLEADO E, DEPHOSPITAL D
WHERE E.CUALIFICACION = 'DOCTOR' AND D.NOMDEPT = 'PEDIATRIA' AND E.DEPAR = D.CODDEPT;

//11

SELECT E.DNI, E.AP1, E.SUELDO, H.CODHOSP
FROM EMPLEADO E, HOSPITAL H, TRABAJA T
WHERE E.DNI = T.DNI AND T.CODHOSP = H.CODHOSP;

//12

SELECT E.DNI, E.AP1, E.SUELDO,COUNT (T.CODHOSP) "NUM_HOSP"
FROM EMPLEADO E, TRABAJA T
WHERE E.DNI = T.DNI
GROUP BY E.DNI, E.AP1, E.SUELDO
ORDER BY "NUM_HOSP" DESC;

//13

SELECT COUNT(*) "INGRESOS"
FROM INGRESOS I
WHERE I.FECHA > '01/01/2019';

//14

SELECT D.NOMDEPT "DEPARTAMENTO", COUNT(*) INGRESOS
FROM INGRESOS I, DEPHOSPITAL D, EMPLEADO E
WHERE I.FECHA > '01/01/2019' AND D.NOMDEPT = 'PEDIATRIA' AND I.DNI = E.DNI AND E.DEPAR = D.CODDEPT
GROUP BY  D.NOMDEPT;

//15

SELECT I.*,H.NOMHOSP, E.AP1
FROM INGRESOS I, HOSPITAL H, EMPLEADO E
WHERE I.DNI = E.DNI AND I.CODHOSP = H.CODHOSP;

//16

SELECT SUM(H.NUMEMP) "TOTAL_EMPLEADOS"
FROM HOSPITAL H;

//17

SELECT H.CODHOSP "CODHOSP",SUM(H.NUMEMP) "TOTAL_EMPLEADOS"
FROM HOSPITAL H
GROUP BY H.CODHOSP;

//18

SELECT MAX(E.SUELDO) "MAXIMO",MIN(E.SUELDO)"MINIMO",AVG(E.SUELDO)"MEDIA"
FROM EMPLEADO E;

//19

SELECT MAX(E.SUELDO) "MAXIMO",MIN(E.SUELDO)"MINIMO",AVG(E.SUELDO)"MEDIA"
FROM EMPLEADO E,PACIENTE P,INGRESOS I
WHERE P.NOMBRE = 'García' AND E.DNI = I.DNI AND I.HISTORIAL = P.HISTORIAL;

//20

SELECT MAX(E.SUELDO) "MAXIMO",MIN(E.SUELDO)"MINIMO",AVG(E.SUELDO)"MEDIA"
FROM EMPLEADO E
WHERE E.DEPAR = 'D3';

//21

SELECT D.CODDEPT "DEPAR", AVG(E.SUELDO)"SUELDO_MEDIO"
FROM DEPHOSPITAL D, EMPLEADO E
WHERE D.CODDEPT = E.DEPAR
GROUP BY D.CODDEPT;

//22

SELECT D.CODDEPT "DEPAR", AVG(E.SUELDO)"SUELDO_MEDIO"
FROM DEPHOSPITAL D, EMPLEADO E
WHERE D.CODDEPT = E.DEPAR 
HAVING AVG(E.SUELDO) > 400
GROUP BY D.CODDEPT;

//23

SELECT E.CUALIFICACION "CUALIFICACION", SUM(E.SUELDO) "TOTAL_SALARIOS"
FROM EMPLEADO E
GROUP BY E.CUALIFICACION
ORDER BY "TOTAL_SALARIOS" DESC;

//24

SELECT H.NOMHOSP "HOSPITAL" , COUNT(E.NOMBRE) "NUM_EMPLEADOS"
FROM EMPLEADO E, HOSPITAL H, TRABAJA T
WHERE E.DNI = T.DNI AND T.CODHOSP = H.CODHOSP
GROUP BY H.NOMHOSP;

//25

SELECT DISTINCT DNI
FROM INGRESOS I; 

//26

SELECT I.HISTORIAL "HISTORIAL", I.FECHA "FECHA", I.CODHOSP "CODH", H.NOMHOSP "HOSPITAL", E.NOMBRE "EMPLEADO", E.DIRECCION "DIRECCION", E.DEPAR "DEPARTAMENTO"
FROM INGRESOS I, HOSPITAL H, EMPLEADO E
WHERE I.CODHOSP = H.CODHOSP AND I.DNI = E.DNI;

//27

SELECT H.CIUDAD, COUNT (*) "INGRESOS"
FROM HOSPITAL H, INGRESOS I
WHERE H.CODHOSP = I.CODHOSP
GROUP BY H.CIUDAD
ORDER BY H.CIUDAD ASC;

//28

SELECT D.NOMDEPT "DEPARTAMENTO", COUNT (*) "INGRESOS"
FROM DEPHOSPITAL D, INGRESOS I, EMPLEADO E
WHERE I.DNI = E.DNI AND E.DEPAR = D.CODDEPT AND I.FECHA > '31/12/2018'
GROUP BY D.NOMDEPT;

//29

SELECT H.CIUDAD "HOSPITAL", D.NOMDEPT "DEPARATAMENTO", COUNT (*) "INGRESOS"
FROM DEPHOSPITAL D, INGRESOS I, EMPLEADO E, HOSPITAL H
WHERE I.DNI = E.DNI AND E.DEPAR = D.CODDEPT AND I.CODHOSP = H.CODHOSP AND I.FECHA > '31/12/2018'
GROUP BY D.NOMDEPT, H.CIUDAD;

//30

SELECT P.NOMBRE, COUNT(*)"VISITAS"
FROM PACIENTE P, INGRESOS I
WHERE I.HISTORIAL =  P.HISTORIAL 
HAVING COUNT(*) > 2
GROUP BY P.NOMBRE;












