//1

SELECT COUNT(*) AS NUMASIGNATURAS
FROM ASIGNATURAS;

SELECT COUNT(*) "NUMASIGNATURAS"
FROM ASIGNATURAS;

//2

SELECT COUNT(*) AS NUMANUALES
FROM ASIGNATURAS
WHERE ANUALIDAD = 'A';

//3

SELECT MAX(ALUMNOS) AS MAXALUMNOS
FROM ASIGNATURAS;

//4

SELECT AVG(ALUMNOS) "MEDIAALUMNOS"
FROM ASIGNATURAS;

//5

SELECT SUM(ALUMNOS) "SUMAALUMNOS"
FROM ASIGNATURAS;

//6

SELECT D.PROFESOR "PROFESOR", COUNT(*) "DOCENCIA"
FROM DOCENCIA D
GROUP BY D.PROFESOR
ORDER BY D.PROFESOR;

//7

SELECT D.PROFESOR "PROFESOR", COUNT(*) "DOCENCIA"
FROM DOCENCIA D
HAVING COUNT(*) > 10
GROUP BY D.PROFESOR
ORDER BY D.PROFESOR;

//8

SELECT SUM(HORAS_TEORIA) "TOTALHORASTEORIA", SUM(HORAS_PRACTICA) "TOTALHORASPRACTICAS"
FROM ASIGNATURAS A, DOCENCIA D
WHERE A.SIGLAS= D.SIGLAS;

//9

SELECT SUM(HORAS_TEORIA) "TOTALHORASTEORIA", SUM(HORAS_PRACTICA) "TOTALHORASPRACTICAS"
FROM ASIGNATURAS A, DOCENCIA D, PROFESORES P
WHERE A.SIGLAS= D.SIGLAS  AND D.PROFESOR = P.CODIGO AND A.ANUALIDAD = 'A' AND P.CODIGO > 30;

//10

SELECT COUNT(*) "NUMASIG" ,AVG(HORAS_PRACTICA) "MEDIAHORASPRACTICA"
FROM ASIGNATURAS A, PROFESORES P, DOCENCIA D
WHERE A.ANUALIDAD = 'A' AND P.CODIGO >30 AND A.SIGLAS = D.SIGLAS AND D.PROFESOR = P.CODIGO;

//11

SELECT MAX(CAPACIDAD) "MAXCAPACIDAD"
FROM LOCALES;

//12

SELECT MAX(CAPACIDAD) "MAXCAPACIDAD"
FROM LOCALES L, ASIGNATURAS A, DOCENCIA D
WHERE A.HORAS_PRACTICA != 0 AND L.CODIGO = D.LOCAL AND A.SIGLAS = D.SIGLAS;

//13

SELECT COUNT(*) "LOCALES1"
FROM LOCALES L
WHERE L.SITUACION LIKE 'Planta Primera%';

//14

SELECT DISTINCT L.SITUACION "SITUACION", COUNT(L.SITUACION) "NUMLOCAL"
FROM LOCALES L
GROUP BY L.SITUACION // el group by es para cada situacion decir el numero de locales
ORDER BY L.SITUACION;

//15

SELECT D.DIA "D", MIN(D.HORA) "PRIMERA_HORA",MAX(D.HORA) "ULTIMA_HORA"
FROM DOCENCIA D
GROUP BY D.DIA
ORDER BY D.DIA;

//16

SELECT ANUALIDAD "A",COUNT(SIGLAS) "NUM_ASIGNATURAS" ,AVG(CREDITOS) "MEDIA_CREDITOS",MIN(ALUMNOS) "MINIMO_ALUMNOS"
FROM ASIGNATURAS
WHERE ANUALIDAD != 'A' OR ANUALIDAD IS NULL
GROUP BY ANUALIDAD
ORDER BY ANUALIDAD;

//17

SELECT  A.SIGLAS "SIGLAS", A.NOMBRE "NOMBRE"
FROM ASIGNATURAS A, DOCENCIA D
WHERE A.SIGLAS = D.SIGLAS 
GROUP BY A.SIGLAS,A.NOMBRE
HAVING COUNT(*) > 9 AND COUNT(*) < 21
ORDER BY A.NOMBRE;

//18

SELECT D.HORA "HORA", COUNT(*) "NUM_DIAS"
FROM DOCENCIA D
WHERE D.SIGLAS = 'Alg'
GROUP BY D.HORA
HAVING COUNT(*) > 1 
ORDER BY COUNT(*) DESC; //ORDER BY NUM_DIAS DESC