-- 1
ALTER TABLE DEPENDIENTE
ADD CONSTRAINT CH_PARENTESCO
CHECK (PARENTESCO IN ('CONYUGE', 'DESCENDIENTE', 'ASCENDIENTE'));

-- 2
UPDATE EMPLEADO SET COD_EMP = '0013' WHERE NOMBRE = 'PEDRO' AND APELLIDO = 'PEREZ';

-- 3
ALTER TABLE EMPLEADO MODIFY CONSTRAINT FK_EMP_SUP DISABLE;
ALTER TABLE DEPARTAMENTO MODIFY CONSTRAINT FK_DEP_JEFE DISABLE;
ALTER TABLE TRABAJA MODIFY CONSTRAINT FK_TRABAJA_COD_EMP DISABLE;

UPDATE EMPLEADO SET COD_EMP = '0013' WHERE NOMBRE = 'PEDRO' AND APELLIDO = 'PEREZ';
UPDATE EMPLEADO SET SUPERVISOR = '0013' WHERE SUPERVISOR = '0001';
UPDATE DEPARTAMENTO SET JEFE = '0013' WHERE JEFE = '0001';
UPDATE TRABAJA SET COD_EMP = '0013' WHERE COD_EMP = '0001';

ALTER TABLE EMPLEADO MODIFY CONSTRAINT FK_EMP_SUP ENABLE;
ALTER TABLE DEPARTAMENTO MODIFY CONSTRAINT FK_DEP_JEFE ENABLE;
ALTER TABLE TRABAJA MODIFY CONSTRAINT FK_TRABAJA_COD_EMP ENABLE;

-- 4
DELETE FROM EMPLEADO WHERE COD_EMP = '1001';

-- 5
ALTER TABLE LOCALIZACIONES RENAME TO ESPACIOS;

-- 6
INSERT INTO DEPARTAMENTO VALUES ('013', 'FORMACION', '0013', CURRENT_DATE);
UPDATE EMPLEADO SET COD_DEP = '013' WHERE COD_EMP = '0013';

-- 7
ALTER TABLE DEPARTAMENTO MODIFY FECHA_JEFE DEFAULT SYSDATE NOT NULL;

-- 8
ALTER TABLE DEPENDIENTE ADD COD_DEPENDIENTE VARCHAR(2) NOT NULL;
ALTER TABLE DEPENDIENTE DROP CONSTRAINT FX_DEPENDIENTE;

-- 9
ALTER TABLE DEPARTAMENTO ADD ( aire VARCHAR(2) DEFAULT 'NO' );

ALTER TABLE DEPARTAMENTO ADD (CONSTRAINT CH_dep_aire CHECK (aire IN ('SI', 'NO')));

UPDATE DEPARTAMENTO SET aire = 'SI'
WHERE cod_dep IN (SELECT D.cod_dep
    FROM departamento D, trabaja T, empleado E
    WHERE D.cod_dep = E.cod_dep AND T.cod_emp = E.cod_emp
    GROUP BY D.cod_dep
    HAVING SUM(horas) < 700);

-- 10
UPDATE EMPLEADO SET SALARIO = SALARIO * 1.15
    WHERE COD_EMP IN (SELECT SUPERVISOR
        FROM EMPLEADO
        GROUP BY SUPERVISOR
        HAVING COUNT(*) > 2);

-- 11
ALTER TABLE PROYECTO ADD (CONSTRAINT FK_ESPACIOS FOREIGN KEY (COD_DEP, LOCALIZA) REFERENCES localizaciones (COD_DEP, LOCALIZA));

-- 12
ALTER TABLE TRABAJA ADD (CONSTRAINT CH_HORAS CHECK (HORAS < 100) NOVALIDATE);

-- 13
ALTER TABLE EMPLEADO MODIFY SALARIO DEFAULT 100;

-- 14
CREATE TABLE SUPERVISORES (
    NSS VARCHAR2(15),
    NOMBRE VARCHAR2(15),
    APELLIDO VARCHAR2(15),
    SALARIO NUMBER,
CONSTRAINT PK_SUPERVISORES PRIMARY KEY (NSS));

-- 15
ALTER TABLE EMPLEADO ADD NIVEL CHAR(1);
ALTER TABLE EMPLEADO ADD CONSTRATINT CH_NIVELEMP_CODELIST CHECK (NIVEL IN ('J', 'S', 'E'));

UPDATE EMPLEADO
    SET NIVEL = 
CASE
    WHEN (SYSDATE-FECHA_NCTO)/365.25 <= 30 THEN 'J'
    WHEN (SYSDATE-FECHA_NCTO)/365.25 BETWEEN 31 AND 50 THEN 'S'
    ELSE 'E'
END;
ALTER TABLE EMPLEADO MODIFY NIVEL CHAR(1) NOT NULL;

SELECT * FROM EMPLEADO ORDER BY FECHA_NCTO;

-- 16
DELETE FROM EMPLEADO
WHERE NOMBRE = 'SONIA' AND APELLIDO = 'LOMA';

-- 17
UPDATE EMPLEADO SET SALARIO = SALARIO * 0.8;
UPDATE EMPLEADO SET SALARIO = 10000 WHERE SALARIO > 10000;
ALTER TABLE EMPLEADO ADD (CONSTRAINT CH_SALARIO CHECK (SALARIO <= 10000));

-- 18
ALTER TABLE DEPENDIENTE DROP (GENERO);

-- 19

