import mysql.connector

connection = mysql.connector.connect(
    user='aaee_24', password='aaee_24', host='eim-srv-mysql.lab.unavarra.es',
    database='aaee_24')
print("DB connected")
cursor = connection.cursor()

cursor.execute("DROP TABLE IF EXISTS DT_DATOS;")
cursor.execute("DROP TABLE IF EXISTS LK_FECHA;")
cursor.execute("DROP TABLE IF EXISTS LK_COMARCA;")

cursor.execute("CREATE TABLE LK_FECHA (ID_FECHA INT AUTO_INCREMENT, DS_FECHA DATE, IND_YEAR INT, IND_MES INT, IND_DIA INT, IND_SEMANA INT,CONSTRAINT CH_Mes CHECK (IND_MES >= 1 and IND_MES <= 12), CONSTRAINT CH_Dia CHECK (IND_DIA >=1 and IND_DIA <= 31), CONSTRAINT CH_Year CHECK (IND_YEAR >= 2004 and IND_YEAR <= 2022), PRIMARY KEY (ID_FECHA));")
cursor.execute("CREATE TABLE LK_COMARCA (DS_NOMBRECOMARCA VARCHAR(255), IND_NOMBREPUEBLO VARCHAR(255), ID_COMARCA INT AUTO_INCREMENT, PRIMARY KEY (ID_COMARCA));")
cursor.execute("CREATE TABLE DT_DATOS (ID_FECHA INT, ID_COMARCA INT, IND_PRECIPITACION FLOAT, IND_TEMPERATURAMAXIMA FLOAT, IND_TEMPERATURAMINIMA FLOAT, IND_TEMPERATURAMEDIA FLOAT, FOREIGN KEY (ID_FECHA) REFERENCES LK_FECHA (ID_FECHA), FOREIGN KEY (ID_COMARCA) REFERENCES LK_COMARCA (ID_COMARCA)) ;")

connection.commit()
connection.close()

