all: fabrica informador materiales peticiones

fabrica: fabrica.c
	gcc fabrica.c -o fabrica

informador: informador.c
	gcc informador.c -o informador
	
materiales: materiales.c
	gcc materiales.c -o materiales
	
peticiones: peticiones.c
	gcc peticiones.c -o peticiones
	
clean:
	rm -f *.o fabrica informador materiales peticiones aka
