all: fabrica informador materiales peticiones

fabrica: fabrica.c
	gcc -o fabrica fabrica.c -Wall

informador: informador.c
	gcc -o informador informador.c -Wall

materiales: materiales.c
	gcc -o materiales materiales.c -Wall

peticiones: peticiones.c
	gcc -o peticiones peticiones.c -Wall

clean:
	rm -f fabrica informador materiales peticiones aka
