# Generated by Django 5.1.2 on 2024-10-15 18:59

import accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", accounts.managers.QuizForgeUsersManager()),
            ],
        ),
    ]
